### ISSUE TITLE
Questions aboud entity linking

### ISSUE THREAD

**Issue by Maydaytyh** [cdhx/QueryAgent#3]
Thank you very much for your work and open-source code. I have a question about entity linking. The paper does not provide a detailed introduction to entity linking.

In the code, there are Golden Entities and non-Golden Entities. Are the results reported in the paper based on non-Golden Entities? If we switch to Golden Entities, how much will the performance improve? Additionally, where are the non-Golden Entities' linking results obtained from?

**Comment by cdhx** [comment]
Hi, thank you for your attention to our work!

Our experiment is based on non-Golden entity linking results.

For GrailQA, GraphQ, and WebQSP, we use the entity linking result provided by [Pangu](https://github.com/dki-lab/Pangu/tree/main). These entity-linking results have been provided in  `data/GrailQA_v1.0/grail_pangu_tiara.json`, `data/GraphQ/graphq_test.json`, and `data/WebQSP/webqsp_test_el.json`.
For MetaQA, as this dataset is too simple, entity linking can be perfectly solved by exact matching.

You can also refer to the `linking_path` variable in [`ag_src/agent_utils/config.py`](https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py)  for the linking file used in our experiment. For example: [`https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py#L66`](https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py#L66)

Switching to the golden entity is expected to improve performance by approximately 5-10 points in F1 score. Please note that this conclusion is based on an early version of our code. We have not yet tested the performance of the golden entity with the latest version.

Please feel free to contact us if you have any questions.

**Comment by Maydaytyh** [comment]
> Hi, thank you for your attention to our work!
> 
> Our experiment is based on non-Golden entity linking results.
> 
> For GrailQA, GraphQ, and WebQSP, we use the entity linking result provided by [Pangu](https://github.com/dki-lab/Pangu/tree/main). These entity-linking results have been provided in `data/GrailQA_v1.0/grail_pangu_tiara.json`, `data/GraphQ/graphq_test.json`, and `data/WebQSP/webqsp_test_el.json`. For MetaQA, as this dataset is too simple, entity linking can be perfectly solved by exact matching.
> 
> You can also refer to the `linking_path` variable in [`ag_src/agent_utils/config.py`](https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py) for the linking file used in our experiment. For example: [`https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py#L66`](https://github.com/cdhx/QueryAgent/blob/main/ag_src/agent_utils/config.py#L66)
> 
> Switching to the golden entity is expected to improve performance by approximately 5-10 points in F1 score. Please note that this conclusion is based on an early version of our code. We have not yet tested the performance of the golden entity with the latest version.
> 
> Please feel free to contact us if you have any questions.

Thank you for your patient response. When there are multiple entity linking results for a question, should these results be placed together in a list as the input for the LLM?

**Comment by cdhx** [comment]
Yes.  In our experiment, we strictly use the entity-linking results provided by Pangu. We just copy the entity linking the result to the inputs. Without the mapping between entity id and entity label, LLM can not directly generate an executable  PyQL function.

**Comment by Maydaytyh** [comment]
Thank you again for your patient response.
