### ISSUE TITLE
About the fb_relation.txt file

### ISSUE THREAD

**Issue by Maydaytyh** [cdhx/QueryAgent#4]
Hello, I couldn't find the fb_relation.txt file mentioned in the ReadMe file. Would it be possible for you to share the generated embedding files (for the questions and relations)? My email is maydaytyh@gmail.com. Thank you!

**Comment by cdhx** [comment]
Sorry for missing this file.

I have uploaded it to `/data/`.

**Comment by Maydaytyh** [comment]
> Sorry for missing this file.
> 
> I have uploaded it to `/data/`.

Thanks for your quick reply! I reviewed the code and it seems that cached embeddings are not being used. For both the query and relations, they are generated using the `faiss_filter(query, relation_list)` function. So I can run it directly without needing to generate the cached files, right?

**Comment by cdhx** [comment]
We have multiple ranking strategies: 
- not use embedding (HS)
- use openai embedding (OE)
- use sentence transformer embedding (ST)

We report the performance of using openai embedding by default in our paper, and also compare the performance when using different ranking strategies in the Appendix (Table 7). 

If you set `openai_embedding` to `False` in `config.py`, there is no need for the openai embedding file and you can directly run it. 

- openai_embedding=False   &   sentence_transformer=False   ->  use Hybrid Search (HS)
- openai_embedding=True   &  sentence_transformer=False   ->  use OpenAI embedding (OE)
- openai_embedding=False   &   sentence_transformer=True  ->  use Sentence Transformer (ST)
- openai_embedding=True   &   sentence_transformer=True   ->  INVALID SETTING

**Comment by Maydaytyh** [comment]
I understand, thank you.
