### ISSUE TITLE
Request for requirements.txt file

### ISSUE THREAD

**Issue by Maydaytyh** [cdhx/QueryAgent#5]
Thank you for sharing this project. While attempting to reproduce your results, I encountered some dependency conflicts when installing the environment. It would be very helpful if you could provide a `requirements.txt` file to ensure consistency and compatibility across environments.

**Comment by cdhx** [comment]
I have uploaded a yaml. 

You can use `conda env create -f environment.yaml` to create a new enviroment.

**Comment by Maydaytyh** [comment]
> I have uploaded a yaml.
> 
> You can use `conda env create -f environment.yaml` to create a new enviroment.

Hi, I met serval conflict when installing the environment, like 
![image](https://github.com/user-attachments/assets/77167e32-3006-4b87-81a8-7a255bb77b7a)
![image](https://github.com/user-attachments/assets/e2f21b9b-65cf-4403-8ed6-bad4e3d7cea2)
![image](https://github.com/user-attachments/assets/fb42c573-ebbc-4a7c-9913-10d8d737c148)
I want to ask if it would be convenient for you to upload the packaged environment file. The direct installation has many dependency issues. Thanks!

**Comment by cdhx** [comment]
I upload another `requirement.txt`. You can try this environment again.

If it still doesn't work, please let me know.

**Comment by Maydaytyh** [comment]
> I upload another `requirement.txt`. You can try this environment again.
> 
> If it still doesn't work, please let me know.

Thanks for your reply! I tried `conda create -n query --file requirements.txt -c https://anaconda.org` and ` conda create -n query --file requirements.txt` respectively. And they didn't work.
<img width="801" alt="image" src="https://github.com/user-attachments/assets/a5c13fa4-8828-4c40-a15f-f7e6d0568556">

<img width="997" alt="image" src="https://github.com/user-attachments/assets/eb27a85b-bce9-4eb9-b07d-3715c0707a86">

**Comment by cdhx** [comment]
If it still does not work, I recommend you install the package based on the module error information.

If it still does not work, I will figure out some ways next week.

DDL in this weekend, sorry)

**Comment by Maydaytyh** [comment]
> If it still does not work, I recommend you install the package based on the module error information.
> 
> If it still does not work, I will figure out some ways next week.
> 
> DDL in this weekend, sorry)

Sure, I'll try it myself again. Wishing you all the best!
